### ISSUE TITLE
UltraNest support

### ISSUE THREAD

**Issue by JohannesBuchner** [matteobreschi/bajes#1]
Would you be interested to add support for https://johannesbuchner.github.io/UltraNest/ ?
The interface should be very similar to dynesty.

UltraNest is a very reliable tuning-parameter-free algorithm. It can be faster than dynesty, especially if you take advantage of vectorization.

It also supports resuming from disk and MPI parallelisation, if that is useful to you.

**Comment by matteobreschi** [comment]
Thanks a lot for your interest.
I am currently working to include `UltraNest` among the samplers. It should be available relatively soon.
I will close this issue as soon as the request is satified.
